### ISSUE TITLE
Golden rune 13 is missing from the calculator. 

### ISSUE THREAD

**Issue by CrypticBore** [sergnio/golden-rune-calculator#1]
As the title states. it would also be nice to able to type the numbers esp if youre like me and just collect a large ammount of runes and for the advanced calculator be able to re edit the value targets. or even be able to select which level you are instead. Anyway thanks for creating this its been a great help.

**Comment by sergnio** [comment]
@CrypticBore I added an input for ya! 
Let me know how it works for you. Thanks for being kind and suggesting a new feature :)

**Comment by CrypticBore** [comment]
OMG no thank you for making this and improving it, this tool has saved me many level losses cause as soon as im at number of runes im scared to loose but isnt enough for a level up i just use the correct ammount of golden runes to level. 

FYI the new features does break it, if you use both the buttons and the text input at the same time least on the brave browser but i wont be doing that. 
Like if you add and minus with the buttons after entering text the golden rune may say 3 but the rune total at the bottom says zero, and if you do this again you can get it to say "NAN" instead of a number.

**Comment by cronin4392** [comment]
Fixed the issue @CrypticBore is talking about in this PR: https://github.com/sergnio/golden-rune-calculator/pull/2
